### ISSUE TITLE
不能播放问题

### ISSUE THREAD

**Issue by HppZ** [chenrensong/ImageLib.UWP#14]
http://www.gif.im/uploads/allimg/130518/1-13051Q03309.gif   这个gif本地或web访问都播放不了，win10系统photos可以播放。

**Comment by chenrensong** [comment]
已经修复

**Comment by HppZ** [comment]
现在可以播放，但上一帧似乎没有清掉，会发生重叠（还是上面那个gif），对win2d流程api都不了解，没法自己改，只能等你改了。谢谢你！

**Comment by chenrensong** [comment]
已经ok了。你更新试试

**Comment by HppZ** [comment]
可以播放没问题了，谢谢你！
另外，错误的原因是什么？

**Comment by chenrensong** [comment]
应该是WIN2D库的bug，用其他方式避免了

发件人: johnsnow__ [mailto:notifications@github.com] 
发送时间: 2016年2月29日 14:41
收件人: chenrensong/ImageLib.UWP ImageLib.UWP@noreply.github.com
抄送: chenrensong chenrensong@outlook.com
主题: Re: [ImageLib.UWP] 不能播放问题 (#14)

可以播放没问题了，谢谢你！
另外，错误的原因是什么？

**Comment by HppZ** [comment]
好的，多谢！

**Comment by HppZ** [comment]
https://github.com/Microsoft/Windows-universal-samples/issues/307   这样可以解决。

**Comment by chenrensong** [comment]
感谢，已按此方案修复

发件人: johnsnow__ [mailto:notifications@github.com] 
发送时间: 2016年3月11日 11:33
收件人: chenrensong/ImageLib.UWP ImageLib.UWP@noreply.github.com
抄送: chenrensong chenrensong@outlook.com
主题: Re: [ImageLib.UWP] 不能播放问题 (#14)

Microsoft/Windows-universal-samples#307 https://github.com/Microsoft/Windows-universal-samples/issues/307  这样可以解决。

**Comment by HppZ** [comment]
不客气。可是那个带Rect参数的重载版本为什么会抛那个异常呢？
